// <auto-generated />
namespace francisca2010
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class francisca2010 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(francisca2010));
        
        string IMigrationMetadata.Id
        {
            get { return "202110270237236_francisca2010"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
